/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas7;

/**
 *
 * @author leorl
 */
public class GUI_MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_MenuUtama.class.getName());

    /**
     * Creates new form GUI_MenuUtama
     */
    public GUI_MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuForm = new javax.swing.JMenu();
        itemKendaraan = new javax.swing.JMenuItem();
        itemMobilElektrik = new javax.swing.JMenuItem();
        itemParkirMobil = new javax.swing.JMenuItem();
        itemKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Utama Sistem Parkir");

        menuHome.setText("Home");
        jMenuBar1.add(menuHome);

        menuForm.setText("Form");
        menuForm.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                menuFormComponentRemoved(evt);
            }
        });

        itemKendaraan.setText("Gui Kendaraan");
        itemKendaraan.addActionListener(this::itemKendaraanActionPerformed);
        menuForm.add(itemKendaraan);

        itemMobilElektrik.setText("Gui Mobil Elektrik");
        itemMobilElektrik.addActionListener(this::itemMobilElektrikActionPerformed);
        menuForm.add(itemMobilElektrik);

        itemParkirMobil.setText("Gui Parkir Mobil");
        itemParkirMobil.addActionListener(this::itemParkirMobilActionPerformed);
        menuForm.add(itemParkirMobil);

        itemKeluar.setText("Keluar");
        itemKeluar.addActionListener(this::itemKeluarActionPerformed);
        menuForm.add(itemKeluar);

        jMenuBar1.add(menuForm);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFormComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_menuFormComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFormComponentRemoved

    private void itemKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKendaraanActionPerformed
GUI_Kendaraan kendaraan = new GUI_Kendaraan();
    kendaraan.setVisible(true);
    }//GEN-LAST:event_itemKendaraanActionPerformed

    private void itemMobilElektrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMobilElektrikActionPerformed
GUI_MobilElektrik elektrik = new GUI_MobilElektrik();
    elektrik.setVisible(true);
    }//GEN-LAST:event_itemMobilElektrikActionPerformed

    private void itemParkirMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemParkirMobilActionPerformed
GUI_ParkirMobil parkir = new GUI_ParkirMobil();
    parkir.setVisible(true);
    }//GEN-LAST:event_itemParkirMobilActionPerformed

    private void itemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKeluarActionPerformed
 System.exit(0);
    }//GEN-LAST:event_itemKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_MenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemKeluar;
    private javax.swing.JMenuItem itemKendaraan;
    private javax.swing.JMenuItem itemMobilElektrik;
    private javax.swing.JMenuItem itemParkirMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuForm;
    private javax.swing.JMenu menuHome;
    // End of variables declaration//GEN-END:variables
}
